// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductionManagement.Infrastructure.Persistence;

#nullable disable

namespace ProductionManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814052112_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductionManagement.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_code");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("uq_orders_order_code");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_date_range", "start_date <= due_date");

                            t.HasCheckConstraint("ck_orders_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_orders_status", "status IN ('Incomplete', 'Completed')");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.PlanAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("adjustment_type");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid?>("AppliedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("applied_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ReversedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reversed_at");

                    b.Property<Guid?>("ReversedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reversed_by");

                    b.Property<int>("ShortageQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("shortage_quantity");

                    b.Property<Guid>("SourceProductionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_production_plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AppliedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ReversedBy");

                    b.HasIndex("SourceProductionPlanId")
                        .HasDatabaseName("ix_plan_adjustments_source_plan");

                    b.ToTable("plan_adjustments", null, t =>
                        {
                            t.HasCheckConstraint("ck_plan_adjustments_shortage", "shortage_quantity > 0");

                            t.HasCheckConstraint("ck_plan_adjustments_status", "status IN ('Applied', 'Reversed')");

                            t.HasCheckConstraint("ck_plan_adjustments_type", "adjustment_type IN ('Manual', 'Automatic')");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.PlanAdjustmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AddOnQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("add_on_quantity");

                    b.Property<Guid>("PlanAdjustmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_adjustment_id");

                    b.Property<Guid>("ProductionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_plan_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanAdjustmentId")
                        .HasDatabaseName("ix_plan_adjustment_items_adjustment");

                    b.HasIndex("ProductionPlanId")
                        .HasDatabaseName("ix_plan_adjustment_items_target_plan");

                    b.HasIndex("PlanAdjustmentId", "ProductionPlanId")
                        .IsUnique()
                        .HasDatabaseName("uq_plan_adjustment_items_adjustment_plan");

                    b.ToTable("plan_adjustment_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_plan_adjustment_items_add_on", "add_on_quantity > 0");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InitialPlannedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("initial_planned_quantity");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("planned_quantity");

                    b.Property<DateOnly>("ProductionDate")
                        .HasColumnType("date")
                        .HasColumnName("production_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "ProductionDate")
                        .IsUnique()
                        .HasDatabaseName("uq_production_plans_order_date");

                    b.ToTable("production_plans", null, t =>
                        {
                            t.HasCheckConstraint("ck_production_plans_initial_quantity", "initial_planned_quantity >= 0");

                            t.HasCheckConstraint("ck_production_plans_quantity", "planned_quantity >= 0");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("actual_quantity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateOnly>("ProductionDate")
                        .HasColumnType("date")
                        .HasColumnName("production_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("OrderId", "ProductionDate")
                        .IsUnique()
                        .HasDatabaseName("uq_production_records_order_date");

                    b.ToTable("production_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_production_records_actual_quantity", "actual_quantity >= 0");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_users_username");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.PlanAdjustment", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AppliedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plan_adjustments_applied_by");

                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_adjustments_created_by");

                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReversedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plan_adjustments_reversed_by");

                    b.HasOne("ProductionManagement.Domain.Entities.ProductionPlan", "SourceProductionPlan")
                        .WithMany()
                        .HasForeignKey("SourceProductionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_adjustments_source_plan");

                    b.Navigation("SourceProductionPlan");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.PlanAdjustmentItem", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.PlanAdjustment", "PlanAdjustment")
                        .WithMany("Items")
                        .HasForeignKey("PlanAdjustmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_adjustment_items_adjustment");

                    b.HasOne("ProductionManagement.Domain.Entities.ProductionPlan", "ProductionPlan")
                        .WithMany()
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_adjustment_items_target_plan");

                    b.Navigation("PlanAdjustment");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionPlan", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.Order", "Order")
                        .WithMany("ProductionPlans")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_plans_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionRecord", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_records_created_by");

                    b.HasOne("ProductionManagement.Domain.Entities.Order", "Order")
                        .WithMany("ProductionRecords")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_records_order");

                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_records_updated_by");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.Order", b =>
                {
                    b.Navigation("ProductionPlans");

                    b.Navigation("ProductionRecords");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.PlanAdjustment", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
