// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductionManagement.Infrastructure.Persistence;

#nullable disable

namespace ProductionManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductionManagement.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_content_type");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_file_name");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_path");

                    b.Property<int?>("ImageSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("image_size_bytes");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ShoeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shoe_code");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ShoeCode")
                        .IsUnique()
                        .HasDatabaseName("uq_orders_shoe_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_image", "(image_path IS NULL AND image_file_name IS NULL AND image_content_type IS NULL AND image_size_bytes IS NULL) OR (image_path IS NOT NULL AND image_file_name IS NOT NULL AND image_content_type IS NOT NULL AND image_size_bytes IS NOT NULL AND image_size_bytes > 0)");

                            t.HasCheckConstraint("ck_orders_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_orders_schedule_dates", "(status = 'Pending' AND start_date IS NULL AND due_date IS NULL) OR (status <> 'Pending' AND start_date IS NOT NULL AND due_date IS NOT NULL AND start_date <= due_date)");

                            t.HasCheckConstraint("ck_orders_status", "status IN ('Pending', 'Incomplete', 'Completed')");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.OrderProductionLine", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_line_id");

                    b.Property<int>("AllocatedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("allocated_quantity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("OrderId", "ProductionLineId")
                        .HasName("pk_order_production_lines");

                    b.HasIndex("ProductionLineId")
                        .HasDatabaseName("ix_order_production_lines_line");

                    b.ToTable("order_production_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_production_lines_allocated", "allocated_quantity > 0");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.PlanAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("adjustment_type");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid?>("AppliedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("applied_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ReversedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reversed_at");

                    b.Property<Guid?>("ReversedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reversed_by");

                    b.Property<int>("ShortageQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("shortage_quantity");

                    b.Property<Guid>("SourceProductionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_production_plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AppliedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ReversedBy");

                    b.HasIndex("SourceProductionPlanId")
                        .HasDatabaseName("ix_plan_adjustments_source_plan");

                    b.ToTable("plan_adjustments", null, t =>
                        {
                            t.HasCheckConstraint("ck_plan_adjustments_shortage", "shortage_quantity > 0");

                            t.HasCheckConstraint("ck_plan_adjustments_status", "status IN ('Applied', 'Reversed')");

                            t.HasCheckConstraint("ck_plan_adjustments_type", "adjustment_type IN ('Manual', 'Automatic')");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.PlanAdjustmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AddOnQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("add_on_quantity");

                    b.Property<Guid>("PlanAdjustmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_adjustment_id");

                    b.Property<Guid>("ProductionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_plan_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanAdjustmentId")
                        .HasDatabaseName("ix_plan_adjustment_items_adjustment");

                    b.HasIndex("ProductionPlanId")
                        .HasDatabaseName("ix_plan_adjustment_items_target_plan");

                    b.HasIndex("PlanAdjustmentId", "ProductionPlanId")
                        .IsUnique()
                        .HasDatabaseName("uq_plan_adjustment_items_adjustment_plan");

                    b.ToTable("plan_adjustment_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_plan_adjustment_items_add_on", "add_on_quantity > 0");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActualQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("actual_quantity");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateOnly>("ProductionDate")
                        .HasColumnType("date")
                        .HasColumnName("production_date");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_line_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ClosedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProductionLineId")
                        .HasDatabaseName("ix_production_days_line");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("Status", "ProductionDate")
                        .HasDatabaseName("ix_production_days_status_date");

                    b.HasIndex("OrderId", "ProductionDate", "ProductionLineId")
                        .IsUnique()
                        .HasDatabaseName("uq_production_days_order_date_line");

                    b.ToTable("production_days", null, t =>
                        {
                            t.HasCheckConstraint("ck_production_days_actual_quantity", "actual_quantity >= 0");

                            t.HasCheckConstraint("ck_production_days_closed_consistency", "(status = 'Closed' AND closed_at IS NOT NULL AND closed_by IS NOT NULL AND actual_quantity IS NOT NULL) OR (status = 'Open' AND closed_at IS NULL AND closed_by IS NULL AND actual_quantity IS NULL)");

                            t.HasCheckConstraint("ck_production_days_status", "status IN ('Open', 'Closed')");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<Guid>("ProductionDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_day_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProductionDayId")
                        .HasDatabaseName("ix_production_entries_day_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("ProductionDayId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_production_entries_day_recorded_at");

                    b.ToTable("production_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_production_entries_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionEntryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("NewNote")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("new_note");

                    b.Property<int?>("NewQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("new_quantity");

                    b.Property<string>("OldNote")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("old_note");

                    b.Property<int?>("OldQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("old_quantity");

                    b.Property<Guid>("ProductionEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_entry_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("ProductionEntryId", "ChangedAt")
                        .HasDatabaseName("ix_production_entry_logs_entry");

                    b.ToTable("production_entry_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_production_entry_logs_action", "action IN ('Create', 'Update', 'Delete')");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_production_lines_code");

                    b.ToTable("production_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_production_lines_sort_order", "sort_order >= 0");

                            t.HasCheckConstraint("ck_production_lines_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InitialPlannedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("initial_planned_quantity");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("planned_quantity");

                    b.Property<DateOnly>("ProductionDate")
                        .HasColumnType("date")
                        .HasColumnName("production_date");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_line_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId")
                        .HasDatabaseName("ix_production_plans_line");

                    b.HasIndex("OrderId", "ProductionDate", "ProductionLineId")
                        .IsUnique()
                        .HasDatabaseName("uq_production_plans_order_date_line");

                    b.ToTable("production_plans", null, t =>
                        {
                            t.HasCheckConstraint("ck_production_plans_initial_quantity", "initial_planned_quantity >= 0");

                            t.HasCheckConstraint("ck_production_plans_quantity", "planned_quantity >= 0");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("RecordingIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("recording_interval_minutes");

                    b.Property<bool>("RemindBeforeDue")
                        .HasColumnType("boolean")
                        .HasColumnName("remind_before_due");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("system_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_system_settings_interval", "recording_interval_minutes BETWEEN 5 AND 480");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_users_username");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.OrderProductionLine", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.Order", "Order")
                        .WithMany("ProductionLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_production_lines_order");

                    b.HasOne("ProductionManagement.Domain.Entities.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_production_lines_line");

                    b.Navigation("Order");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.PlanAdjustment", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AppliedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plan_adjustments_applied_by");

                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_adjustments_created_by");

                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReversedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plan_adjustments_reversed_by");

                    b.HasOne("ProductionManagement.Domain.Entities.ProductionPlan", "SourceProductionPlan")
                        .WithMany()
                        .HasForeignKey("SourceProductionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_adjustments_source_plan");

                    b.Navigation("SourceProductionPlan");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.PlanAdjustmentItem", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.PlanAdjustment", "PlanAdjustment")
                        .WithMany("Items")
                        .HasForeignKey("PlanAdjustmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_adjustment_items_adjustment");

                    b.HasOne("ProductionManagement.Domain.Entities.ProductionPlan", "ProductionPlan")
                        .WithMany()
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_adjustment_items_target_plan");

                    b.Navigation("PlanAdjustment");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionDay", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ClosedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_production_days_closed_by");

                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_days_created_by");

                    b.HasOne("ProductionManagement.Domain.Entities.Order", "Order")
                        .WithMany("ProductionDays")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_days_order");

                    b.HasOne("ProductionManagement.Domain.Entities.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_days_line");

                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_days_updated_by");

                    b.Navigation("Order");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionEntry", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_entries_created_by");

                    b.HasOne("ProductionManagement.Domain.Entities.ProductionDay", "ProductionDay")
                        .WithMany("Entries")
                        .HasForeignKey("ProductionDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_entries_day");

                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_entries_updated_by");

                    b.Navigation("ProductionDay");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionEntryLog", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_entry_logs_changed_by");

                    b.HasOne("ProductionManagement.Domain.Entities.ProductionEntry", null)
                        .WithMany()
                        .HasForeignKey("ProductionEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_entry_logs_entry");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionPlan", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.Order", "Order")
                        .WithMany("ProductionPlans")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_plans_order");

                    b.HasOne("ProductionManagement.Domain.Entities.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_plans_line");

                    b.Navigation("Order");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.SystemSettings", b =>
                {
                    b.HasOne("ProductionManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_system_settings_updated_by");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.Order", b =>
                {
                    b.Navigation("ProductionDays");

                    b.Navigation("ProductionLines");

                    b.Navigation("ProductionPlans");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.PlanAdjustment", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProductionManagement.Domain.Entities.ProductionDay", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
